apiVersion: v1
kind: ConfigMap
metadata:
  name: agent
data:
  anthropic-model: "claude-sonnet-4-20250514"
  anthropic-summary-model: "claude-haiku-4-5-20251001"
  context-window-size: "20"
  context-summarize-trigger: "30"
  context-summary-max-tokens: "512"
