name: Build and Deploy to Dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - '.gitignore'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLUSTER: plugins-dev-k8s
  NS: agent

jobs:
  build-server:
    uses: ./.github/workflows/build-push-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      registry: ghcr.io
      image_name: ${{ github.repository }}
      tag: dev-${{ github.sha }}
      additional_tag: dev-latest

  deploy:
    needs: [build-server]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_CI_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER }}

      - name: Update deployment files
        run: |
          TAG="dev-${{ github.sha }}"
          sed -i "s|image: busybox|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/server:${TAG}|" deploy/01_server.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl -n ${{ env.NS }} apply -f deploy/dev
          kubectl -n ${{ env.NS }} apply -f deploy/01_server.yaml
          kubectl -n ${{ env.NS }} rollout status deployment/server --timeout=300s
